### PR TITLE
Integrate all SilasUI changes into magadan and default

### PR DESCRIPTION
**Pull request by Mimoja**
This removes the dedicated SilasUI and removes the magadan settings-screen,
which will now be using the default settings screen.

Signed-off-by: Mimoja <git@mimoja.de>

### CODE REVIEW

**Comment by Mimoja** [comment]
@silasg @seva-today please confirm that you are happy with these changes and that I am not violating your visions

**Comment by silasg** [comment]
@Mimoja absolutely! I'd love to see my proposal in the default. For more controversial features like temperature graph or the EXPERIMENTAL profile backup/ restore I also could imagine that we don't show them in settings screen but require users to manually enable them by editing their settings file. This should make it at least a little harder to mess up stuff by accident.

**Comment by Mimoja** [comment]
okay, cool :)

**Comment by silasg** [comment]
just read the code and saw that you already integrated the options in the settings and tagging restore as experimental. of course, I'm also fine with that solution :)

**Pull request merged**
